[build-system]
requires = ["setuptools", "wheel"]

[tool.poetry]
name = "klingon_serial"
version = "0.0.1"
description = ""
authors = ["Your Name <your.email@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
uuid = "^1.30"
datetime = "^4.3"
netifaces = "^0.10.9"
pytest = "^6.2.4"
setuptools = "^57.4.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
