name: klingon-serial-unit-tests

on: 
    push:
    workflow_dispatch:
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
        BRANCH: ${{ github.ref }}
        GITHUB_USERNAME: ${{ github.actor }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make check-packages
    - name: Build and test
      run: |
        pip install .
        make sdist
        make wheel
        make test