name: OpenFaaS Docker Build

on:
  push:
    branches:
      - main
    paths:
      - 'openfaas/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

      with:
        install: true
        version: latest
        buildkitd-flags: --debug
        driver-opts: image=moby/buildkit:master
        use: true

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Run make build
      run: |
        cd openfaas
        make check-buildx
        make build
