name: Docker Build Pre-Checks

on:
  push:
    branches:
      - '*'
    paths:
      - 'openfaas/**'
      - '.github/workflows/openfaas-pre-docker-build-pr.yaml'
      - '.github/workflows/openfaas-docker-build.yaml'
  workflow_dispatch:
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  prepare-version-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests setuptools

    - name: Calculate new release number
      id: versioning
      run: |
        # Import openfaas/build.py
        import sys
        import os
        sys.path.append(os.path.join(os.environ['GITHUB_WORKSPACE'], 'openfaas'))
        from build import fetch_latest_tag, increment_version
        image_name = 'djh00t/klingon-serial'
        latest_tag = fetch_latest_tag(image_name)
        new_version = increment_version(latest_tag, 'patch')  # Assuming we're doing a patch release
        with open(os.getenv('GITHUB_ENV'), 'a') as f:
           f.write(f"new_version={new_version}\n")
      shell: python

    - name: Create or update PR with new release number
      uses: actions/github-script@v6
      with:
        script: |
          const github = require('@actions/github');
          const core = require('@actions/core');
          const context = github.context;
          const newVersion = core.getInput('new_version');
          const branchName = `release-${newVersion}`;
          const title = `Release ${newVersion}`;
          const body = '## Changelog\n<!-- markdown-changelog-generator -->';
          const base = 'main';
          const labels = ['pre-release'];

          // Create or update pull request
          await github.rest.pulls.createOrUpdate({
            ...context.repo,
            title,
            body,
            head: branchName,
            base,
            labels,
            draft: false
          });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}


