name: OpenFaaS Docker Build

on:
  push:
    branches:
      - main
    paths:
      - 'openfaas/**'
      - '.github/workflows/openfaas-docker-build.yaml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Ensure Docker is installed and running
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io
        sudo usermod -aG docker $USER
        sudo systemctl enable docker
        sudo systemctl start docker
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true
        version: latest
        buildkitd-flags: --debug
        driver-opts: image=moby/buildkit:master
        use: true
      id: buildx

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Run make build
      run: |
        cd openfaas
        rm -rf ../requirements.txt
        cp requirements.txt ../
        make check-buildx
        make build
      env:
        BUILDX_BUILDER: ${{ steps.buildx.outputs.name }}
