name: Pre-PR Merge CI

# Controls when the action will run. 
on:
  push: 
    branches:
      - '*'
    tags:
      - '*'
    paths:
      - '**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  pre-pr-merge:
    permissions:
      contents: write
      pull-requests: write
    if: (github.event_name == 'push' && github.ref != 'refs/heads/main') || (github.event_name == 'pull_request' && github.base_ref == 'main') || (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.ref }}
      GITHUB_USERNAME: ${{ github.actor }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          make check-packages
      - name: "Increment version number"
        run: |
          make update-version
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: Build and test
        run: |
          pip install .
          make sdist
          make wheel
          make test
      - name: Open a pull request to main
        if: github.ref != 'refs/heads/main'
        run: |
          branch_name=$(echo ${GITHUB_REF#refs/heads/})
          gh pr create --title "Merge $branch_name into main" --body "This is an automated PR to merge changes from $branch_name into main." --base main --head $branch_name --repo ${{ github.repository }}
