name: Pre-PR Merge CI

# Controls when the action will run. 
on:
  push: 
    branches:
      - '*'
    paths:
      - '**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test:
    if: (github.event_name == 'push' && github.ref != 'refs/heads/main') || (github.event_name == 'pull_request' && github.base_ref == 'main') || (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.ref }}
      GITHUB_USERNAME: ${{ github.actor }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          make check-packages
      - name: "Increment version number"
        run: |
          make update-version
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: Build and test
        run: |
          pip install .
          make sdist
          make wheel
          make test
      - name: Push to TestPyPI
        run: |
          make upload-test TEST_PYPI_USER_AGENT=${{ secrets.TEST_PYPI_USER_AGENT }} || echo "Push to TestPyPI failed, but the workflow continues."
