name: Pre-PR Merge CI

# Controls when the action will run. 
on:
  push: 
    branches:
      - '*'
    tags:
      - '*'
    paths:
      - '**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  pre-pr-merge:
    permissions:
      contents: write
      pull-requests: write
    if: (github.event_name == 'push' && github.ref != 'refs/heads/main') || (github.event_name == 'pull_request' && github.base_ref == 'main') || (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.ref }}
      GITHUB_USERNAME: ${{ github.actor }}

    steps:
      - uses: actions/checkout@v3-node20
      - name: Set up Python 3.x
        uses: actions/setup-python@v3-node20
        with:
          python-version: 3.x
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          make check-packages
      - name: Build and test
        run: |
          pip install .
          make sdist
          make wheel
          make test
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet origin/${{ github.base_ref }}...HEAD; then
            echo "No changes detected."
            echo "has_changes=no" >> $GITHUB_ENV
          else
            echo "Changes detected."
            echo "has_changes=yes" >> $GITHUB_ENV
          fi
      - name: pull-request
        if: env.has_changes == 'yes'
        uses: diillson/auto-pull-request@latest
        with:
          destination_branch: "main"
          pr_label: "auto-pr"                               # Comma-separated list (no spaces)
          pr_draft: true                                    # Creates pull request as draft
          pr_allow_empty: true                              # Creates pull request even if there are no changes
      - name: output-url
        run: echo ${{steps.open-pr.outputs.pr_url}}
      - name: output-number
        run: echo ${{steps.open-pr.outputs.pr_number}}
      - name: output-created
        run: echo ${{steps.open-pr.outputs.pr_created}}
      - name: output-has-changed-files
        run: echo ${{steps.open-pr.outputs.has_changed_files}}