name: Pre-PR Merge CI

# Controls when the action will run. 
on:
  pull_request:
    paths:
      - 'klingon_serial/**'
      - 'tests/**'
      - 'VERSION'
      - 'Makefile'
      - 'setup.py'
      - 'requirements.txt'
      - '!openfaas/**'
      - '!.github/workflows/openfaas-pre-docker-build-pr.yaml'
      - '!.github/workflows/openfaas-docker-build.yaml'
    branches:
      - main
  workflow_dispatch:
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  pre-pr-merge:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.ref }}
      GITHUB_USERNAME: ${{ github.actor }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          make check-packages
      - name: Build and test
        run: |
          pip install .
          make sdist
          make wheel
          make test
